### ISSUE TITLE
What is this app called?

### ISSUE THREAD

**Issue by arrested-developer** [fac-14/eastendtradesguild#2]

**Comment by arrested-developer** [comment]
Key words: rent, rental, transparency, compare, comparable

**Comment by KrissieN** [comment]
Guys, am I coming back to see you tomorrow or next Wednesday? I have it in my diary for 2pm tomorrow, but I think that's incorrect?

**Comment by dupreesi** [comment]
Hi Krissie, yes we are all set for tomorrow 2pm. As we are almost finished with the wire framing you could also come around this afternoon. What do you prefer?
It'd be super important for us to get the confirmation about what data fields are (not) important by the Royal Institution of Chartered Surveyors. 
Thank you.

**Comment by arrested-developer** [comment]
rent checker has also been suggested.

Closing as client is happy 😄
